# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stellarflow_channels.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'stellarflow_channels.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astellarflow_channels.proto\x12\x14stellarflow.channels\"\x83\x01\n\x0bPriceUpdate\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x03\x12\x0e\n\x06volume\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x10\n\x08sequence\x18\x05 \x01(\r\x12\r\n\x05\x66lags\x18\x06 \x01(\r\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x07 \x01(\r\"K\n\x10SignatureRequest\x12\x0f\n\x07tx_hash\x18\x01 \x01(\x0c\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x12\n\naccount_id\x18\x03 \x01(\r\"A\n\x11SignatureResponse\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x86\x01\n\x0eTelemetryFrame\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\x0c\x12\r\n\x05price\x18\x02 \x01(\x03\x12\x0e\n\x06volume\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x10\n\x08sequence\x18\x05 \x01(\r\x12\r\n\x05\x66lags\x18\x06 \x01(\r\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x07 \x01(\r\"`\n\x0fTelemetryBundle\x12\x34\n\x06\x66rames\x18\x01 \x03(\x0b\x32$.stellarflow.channels.TelemetryFrame\x12\x17\n\x0f\x62undle_sequence\x18\x02 \x01(\x04\"N\n\tHeartbeat\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\r\n\x05\x61live\x18\x03 \x01(\x08\x12\x0e\n\x06status\x18\x04 \x01(\t\"l\n\x0fMessageEnvelope\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x0e\n\x06source\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stellarflow_channels_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEUPDATE']._serialized_start=53
  _globals['_PRICEUPDATE']._serialized_end=184
  _globals['_SIGNATUREREQUEST']._serialized_start=186
  _globals['_SIGNATUREREQUEST']._serialized_end=261
  _globals['_SIGNATURERESPONSE']._serialized_start=263
  _globals['_SIGNATURERESPONSE']._serialized_end=328
  _globals['_TELEMETRYFRAME']._serialized_start=331
  _globals['_TELEMETRYFRAME']._serialized_end=465
  _globals['_TELEMETRYBUNDLE']._serialized_start=467
  _globals['_TELEMETRYBUNDLE']._serialized_end=563
  _globals['_HEARTBEAT']._serialized_start=565
  _globals['_HEARTBEAT']._serialized_end=643
  _globals['_MESSAGEENVELOPE']._serialized_start=645
  _globals['_MESSAGEENVELOPE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
